name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build -v ./...

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v ./...
